BASE_URL = "https://stellarburgers.nomoreparties.site/"
REGISTER_URL = f"{BASE_URL}register"
PASSWORD_RECOVERY_URL = f"{BASE_URL}forgot-password"
LOGIN_URL = f"{BASE_URL}login"
PROFILE_URL = f"{BASE_URL}account/profile"
